server:
  port: 15001

spring:
  application:
    name: "config"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/davidwushi1145/configServer.git
          default-label: main
  rabbitmq:
    stream:
      host: localhost
      port: 5672
      username: guest
      password: guest

#暴露bus-refresh节点，通过此节点刷新配置
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
