server:
  port: 18001

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: "eurekaServer18001"
  client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: "http://eurekaServer18000:18000/eureka/"

spring:
  application:
    name: Eureka18001

logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG