server:
  port: 12000

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/"
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

spring:
  main:
    web-application-type: reactive
  application:
    name: Gateway12000
  cloud:
    gateway:
      routes:
        - id: consumer1
          uri: lb://consumer
          predicates:
            - Path=/cart/getCartByUserId/**
          filters:
            - name: CircuitBreaker
              args:
                name: backendA
                fallbackUri: forward:/fallback
        - id: provider1
          uri: lb://provider
          predicates:
            - Path=/user/getUserById/**
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                - GET
                - POST
                allowedHeaders:
                - "*"
                maxAge: 3600

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 30
        minimum-number-of-calls: 1
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 2s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      backendA:
        base-config: default


logging:
  level:
    org:
      springframework:
        web: DEBUG
        http: DEBUG